version: "3.8"

services:
  backend:
    image: julesgresset/hellokitchen-backend:${BACKEND_IMAGE_TAG}
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env